# Generated by Django 4.2.5 on 2023-10-03 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('video_url', models.URLField()),
                ('video_duration', models.IntegerField()),
                ('products', models.ManyToManyField(to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='LessonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_view_during', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('VIEWED', 'Viewed'), ('NOT_VIEWED', 'Not Viewed')], default='NOT_VIEWED', max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='lessonview',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='user_lesson_unique_constraint'),
        ),
    ]
