# Generated by Django 4.2.5 on 2023-10-06 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='last_time_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 3, 45, 42, 971617, tzinfo=datetime.timezone.utc)),
        ),
    ]
