# Generated by Django 4.2.5 on 2023-10-07 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('study', '0003_remove_lessonview_last_time_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(related_name='lessons', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='last_view_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 12, 9, 33, 930959, tzinfo=datetime.timezone.utc)),
        ),
    ]
