# Generated by Django 4.2.5 on 2023-10-08 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_lessonview_last_view_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='last_view_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 13, 17, 13, 408133, tzinfo=datetime.timezone.utc)),
        ),
    ]
