# Generated by Django 4.2.5 on 2023-10-08 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_alter_lessonview_last_view_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='last_view_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 13, 19, 47, 220834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='study.lesson'),
        ),
    ]
